# Generated by Django 3.0 on 2020-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_keypair_bits'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypair',
            name='ident',
            field=models.IntegerField(default=0),
        ),
    ]
