# Generated by Django 3.0 on 2020-03-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200313_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypair',
            name='used',
            field=models.BooleanField(),
        ),
    ]
