# Generated by Django 3.0 on 2020-03-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200314_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificateautority',
            old_name='privete_key',
            new_name='private_key',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='bits',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='keypair',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='keypair',
            name='public_key',
        ),
    ]
