# Generated by Django 3.0 on 2020-03-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200314_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypair',
            name='private_key',
            field=models.CharField(default='', max_length=999999),
        ),
        migrations.AddField(
            model_name='keypair',
            name='public_key',
            field=models.CharField(default='', max_length=999999),
        ),
    ]
