# Generated by Django 3.0 on 2020-03-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200314_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificateautority',
            name='ident',
            field=models.IntegerField(default=0),
        ),
    ]
