# Generated by Django 3.0 on 2020-03-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200314_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='self_signed',
        ),
    ]
