# Generated by Django 3.0 on 2020-03-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_certificate_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypair',
            name='used',
        ),
    ]
